#You can eidt the color scheme in source/css/_base/variable.styl

photo: /images/IGGG_l.png

email:
twitter: "@IGGGorg"
facebook:
googleplus:
github: IGGG
pinterest:
linkedin:
instagram:
zhihu:
weibo:
renren:


addthis:
  enable: false
  pubid:
  facebook: false
  twitter: true
  google: false
  pinterest: false

fancybox: true

#
bighomepage: true

#Use cdnjs' CDN
usecdn: false

google_analytics:
rss:

forvirgo: false
