name: Deploy to Heroku

on:
  push:
    branches:
    - staging

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build by Hexo
      run: |
        npm install
        node_modules/.bin/hexo clean
        node_modules/.bin/hexo generate
    - name: Deploy to staging
      env:
        DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
        GIT_NAME: IGGGorg
        GIT_EMAIL: contact@iggg.org
      run: |
        npm install hexo-deployer-heroku --save
        ./.github/scripts/heroku-setup.bash
        ./.github/scripts/deploy.bash _staging_config.yml
      shell: bash
