name: Tweet to update page by git diffs

on:
  push:
    branches:
    - tweet

jobs:
  tweet:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build tweet message
      uses: matsubara0507/actions/outputs@master
      id: message
      env:
        TARGET_BRANCH: HEAD^
      with:
        script_path: ./.github/scripts/tweet-message.bash
    - name: Tweet
      uses: matsubara0507/actions/tweet@master
      with:
        consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
        consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        message: ${{ steps.message.outputs.result }}
